#!/usr/bin/env bash
# install.sh — first-time setup for media-manager
# Run once after cloning to prepare the environment and generate config.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ── Colours ───────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
    BOLD='\033[1m'; GREEN='\033[32m'; CYAN='\033[36m'
    YELLOW='\033[33m'; RED='\033[31m'; RESET='\033[0m'
else
    BOLD=''; GREEN=''; CYAN=''; YELLOW=''; RED=''; RESET=''
fi

info()  { echo -e "  ${CYAN}→${RESET}  $*"; }
ok()    { echo -e "  ${GREEN}✓${RESET}  $*"; }
warn()  { echo -e "  ${YELLOW}!${RESET}  $*"; }
fail()  { echo -e "  ${RED}✗${RESET}  $*"; exit 1; }

echo -e "\n${BOLD}  media-manager install${RESET}\n"

# ── Check Python 3.9+ ─────────────────────────────────────────────────────────
info "Checking Python version..."
PYTHON=""
for candidate in python3 python; do
    if command -v "$candidate" &>/dev/null; then
        ver=$("$candidate" -c "import sys; print(sys.version_info[:2])" 2>/dev/null || echo "(0, 0)")
        major=$(echo "$ver" | tr -d '()' | awk -F', ' '{print $1}')
        minor=$(echo "$ver" | tr -d '()' | awk -F', ' '{print $2}')
        if [[ "$major" -ge 3 && "$minor" -ge 9 ]]; then
            PYTHON="$candidate"
            break
        fi
    fi
done

if [[ -z "$PYTHON" ]]; then
    fail "Python 3.9 or higher is required but was not found. Install it and re-run."
fi
ok "Found $($PYTHON --version)"

# ── Create virtual environment ────────────────────────────────────────────────
info "Creating virtual environment in .venv..."
if [[ -d ".venv" ]]; then
    warn ".venv already exists — skipping creation"
else
    "$PYTHON" -m venv .venv
    ok "Created .venv"
fi

# ── Install requirements ──────────────────────────────────────────────────────
info "Installing Python dependencies..."
.venv/bin/pip install --quiet -r requirements.txt
ok "Dependencies installed"

# ── Ask for port ─────────────────────────────────────────────────────────────
echo
read -rp "  Port to listen on [default: 10400]: " PORT_INPUT
PORT="${PORT_INPUT:-10400}"
ok "Using port ${PORT}"

# ── Generate secrets ──────────────────────────────────────────────────────────
info "Generating AUTH_SECRET_KEY..."
AUTH_SECRET_KEY=$("$PYTHON" -c "import secrets; print(secrets.token_hex(32))")
ok "AUTH_SECRET_KEY generated"

info "Generating PLEX_CLIENT_ID..."
PLEX_CLIENT_ID=$("$PYTHON" -c "import uuid; print(uuid.uuid4())")
ok "PLEX_CLIENT_ID generated"

# ── Create config directory ───────────────────────────────────────────────────
mkdir -p config

# ── Write config/.env ────────────────────────────────────────────────────────
ENV_FILE="config/.env"
if [[ -f "$ENV_FILE" ]]; then
    # File exists — update PORT only, preserve everything else
    if grep -q "^PORT=" "$ENV_FILE"; then
        sed -i "s/^PORT=.*/PORT=${PORT}/" "$ENV_FILE"
    else
        echo "PORT=${PORT}" >> "$ENV_FILE"
    fi
    # Preserve existing AUTH_SECRET_KEY and PLEX_CLIENT_ID
    ok "Updated PORT in existing $ENV_FILE"
else
    cat > "$ENV_FILE" <<EOF
# media-manager configuration
# Generated by install.sh — edit to configure your services.
# Run ./bin/deploy.sh to start, then visit http://localhost:${PORT}/setup
# to complete setup via the web wizard.

PORT=${PORT}
AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
PLEX_CLIENT_ID=${PLEX_CLIENT_ID}

# Set to true once you have completed the setup wizard.
# The wizard sets this automatically.
SETUP_COMPLETE=false
EOF
    ok "Created $ENV_FILE"
fi

# ── Check for docker / podman-compose ────────────────────────────────────────
echo
info "Checking for container runtime..."
if command -v podman-compose &>/dev/null; then
    ok "Found: podman-compose"
elif command -v docker &>/dev/null; then
    ok "Found: docker compose"
else
    warn "Neither podman-compose nor docker compose was found."
    warn "Install one before running ./bin/deploy.sh"
fi

# ── Crontab setup ────────────────────────────────────────────────────────────
echo
ENSURE_SCRIPT="$SCRIPT_DIR/bin/media-manager-ensure-running.sh"
ENSURE_LOG="$SCRIPT_DIR/logs/ensure.log"
CRON_REBOOT="@reboot $ENSURE_SCRIPT >>$ENSURE_LOG 2>&1"
CRON_POLL="*/5 * * * * $ENSURE_SCRIPT >>$ENSURE_LOG 2>&1"

if ! command -v crontab &>/dev/null; then
    warn "crontab not found — skipping automatic startup setup."
    warn "To keep the container running, add these to your crontab manually:"
    warn "  @reboot $ENSURE_SCRIPT >>$ENSURE_LOG 2>&1"
    warn "  */5 * * * * $ENSURE_SCRIPT >>$ENSURE_LOG 2>&1"
else
    EXISTING_CRON=$(crontab -l 2>/dev/null || true)
    ALREADY_SET=false
    if echo "$EXISTING_CRON" | grep -qF "$ENSURE_SCRIPT"; then
        ALREADY_SET=true
    fi

    if [[ "$ALREADY_SET" == true ]]; then
        ok "Crontab entries already present — skipping"
    else
        echo
        echo -e "  ${BOLD}Crontab setup${RESET}"
        echo -e "  The following entries keep the container running after reboot:"
        echo -e "  ${DIM}  @reboot    $ENSURE_SCRIPT${RESET}"
        echo -e "  ${DIM}  */5 * * *  $ENSURE_SCRIPT${RESET}"
        echo
        read -rp "  Add these to your crontab? [Y/n]: " CRON_ANSWER
        CRON_ANSWER="${CRON_ANSWER:-Y}"
        if [[ "$CRON_ANSWER" =~ ^[Yy] ]]; then
            NEW_CRON="${EXISTING_CRON:+${EXISTING_CRON}$'\n'}${CRON_REBOOT}"$'\n'"${CRON_POLL}"
            echo "$NEW_CRON" | crontab -
            ok "Crontab entries added"
        else
            warn "Skipped — add them manually if you want the container to survive reboots."
        fi
    fi
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo
echo -e "  ${GREEN}${BOLD}Setup complete.${RESET}  Run ${CYAN}./bin/deploy.sh${RESET} to start, then visit ${CYAN}http://localhost:${PORT}/setup${RESET}"
echo
